# Surge project manifest
[package]
name = "sigil"
version = "0.1.0"

[run]
main = "main.sg"

[version]
version = "0.1.0-dev"
commit = "113eed92033a"
message = "Enhance LLVM emission and diagnostic handling"
built = "2026-01-21T09:52:29Z"
